# Generated by Django 2.2.6 on 2021-03-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20210314_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(
                help_text='Дайте описание группы',
                verbose_name='Описание группы'),
        ),
    ]
