# Generated by Django 2.2.6 on 2021-04-01 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(help_text='Добавьте комментарий', max_length=100, verbose_name='Текст комментария'),
        ),
    ]
